### ISSUE TITLE
Request - a colour SVG logo

### ISSUE THREAD

**Issue by jamescridland** [AntennaPod/Branding#10]
Hello!

https://github.com/AntennaPod/Branding/tree/master/Logo

In this folder, I'd be very grateful for a colour SVG logo. I will be adding links to AntennaPod in Podnews podcast pages - [here's an example](https://podnews.net/podcast/i5r8) - and would like to be using the correct logo (but we're SVG-only).

**Comment by jamescridland** [comment]
(I'm using https://github.com/AntennaPod/Branding/blob/master/Source%20Files/antennapod_official.svg which is not, quite, the right logo)

**Comment by keunes** [comment]
Hi @jamescridland,

Sorry for the late relpy. We're working on it :) (Might take a month or two, though.)

**Comment by ByteHamster** [comment]
Sorry for the long delay @jamescridland. We finally have an updated logo design that is also available as SVG. You can find the file here: https://github.com/AntennaPod/Branding/blob/master/Logo/logo-icon.svg

**Comment by jamescridland** [comment]
Awesome, much nicer, thank you.

In place [over here and in more than half a million similar pages](https://podnews.net/podcast/i8xe9#all)
